volumes:
  psql:
services:
  psql:
    image: postgres # this uses the 'latest' version
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example # only do this in development
    volumes:
      - psql:/var/lib/postgresql/data # save data between restarts
  server:
    build: .
    ports:
      - 3000:3000
    env_file: ./docker.env
    environment:
      POSTGRESQL: postgres://postgres:example@psql:5432/postgres
